INSERT INTO `tb_alternatif` (`kode_alternatif`, `nama_alternatif`, `kelas`) VALUES
	('a1', 'amran wali', '1a'),
	('a2', 'arinal khaira', '1a'),
	('a3', 'azril ilham', '1a'),
	('a4', 'dedek subhan kurniawan', '1a'),
	('a5', 'desga farizie pratama', '1a'),
	('a6', 'farid alqausar', '1a'),
	('a7', 'hasnidar', '1a'),
	('a8', 'jannatul ula', '1a'),
	('a9', 'lidia anggraini', '1a'),
	('a10', 'lisma tiara', '1a'),
	('a11', 'm. adrian', '1a'),
	('a12', 'm. naufal', '1a'),
	('a13', 'maulinar', '1a'),
	('a14', 'mizan', '1a'),
	('a15', 'muhammad fajar', '1a'),
	('a16', 'muhammad sultan', '1a'),
	('a17', 'muizzatul hasanah', '1a'),
	('a18', 'nadiyul kaffa', '1a'),
	('a19', 'nayla sakina', '1a'),
	('a20', 'nisa humaira', '1a'),
	('a21', 'nurmaida', '1a'),
	('a22', 'rahmatul abrar', '1a'),
	('a23', 'riskia amanda', '1a'),
	('a24', 'rizkan ananda', '1a'),
	('a25', 'rizki', '1a'),
	('a26', 'sakia nabila', '1a'),
	('a27', 'salman alfarisi', '1a'),
	('a28', 'amelia putr', '1b'),
	('a29', 'aura humaira', '1b'),
	('a30', 'badratun nafis', '1b'),
	('a31', 'cut tiara kanash', '1b'),
	('a32', 'debi nikmah nasution', '1b'),
	('a33', 'emi khan', '1b'),
	('a34', 'fajar khalili', '1b'),
	('a35', 'fauzan rizk', '1b'),
	('a36', 'hayatun mauliza', '1b'),
	('a37', 'khalil mukhalad', '1b'),
	('a38', 'maulana', '1b'),
	('a39', 'miftahul janna', '1b'),
	('a40', 'miftahul rizk', '1b'),
	('a41', 'muammi', '1b'),
	('a42', 'muhammad maulidin', '1b'),
	('a43', 'munzir', '1b'),
	('a44', 'mustaf', '1b'),
	('a45', 'naila rahmah', '1b'),
	('a46', 'najmul ramadanus', '1b'),
	('a47', 'nazilul fikri', '1b'),
	('a48', 'rahmat afand', '1b'),
	('a49', 'raihan', '1b'),
	('a50', 'raysa saqil', '1b'),
	('a51', 'rizki fahri', '1b'),
	('a52', 'saprian', '1b'),
	('a53', 'saski', '1b'),
	('a54', 'alif alfarisy', '2a'),
	('a55', 'anggi fitria', '2a'),
	('a56', 'askiya ulhaqqi', '2a'),
	('a57', 'eza saputra', '2a'),
	('a58', 'fadhlur rahman', '2a'),
	('a59', 'fari alfathir', '2a'),
	('a60', 'm. aris', '2a'),
	('a61', 'muhammad agil', '2a'),
	('a62', 'muhammad al-azqiai', '2a'),
	('a63', 'muhammad rafiqi', '2a'),
	('a64', 'muhammad reza', '2a'),
	('a65', 'mulqi adhil', '2a'),
	('a66', 'muslem', '2a'),
	('a67', 'nailul una', '2a'),
	('a68', 'neliana', '2a'),
	('a69', 'putriani', '2a'),
	('a70', 'rahmazani', '2a'),
	('a71', 'raisa agustina', '2a'),
	('a72', 'revi furqan', '2a'),
	('a73', 'safira nabila', '2a'),
	('a74', 'samwil', '2a'),
	('a75', 'tisa humaira', '2a'),
	('a76', 'yusmandar', '2a'),
	('a77', 'ahmad thairan ababil', '2b'),
	('a78', 'ajirna', '2b'),
	('a79', 'akramul kiram', '2b'),
	('a80', 'asyifa rahmah', '2b'),
	('a81', 'devi jurnita', '2b'),
	('a82', 'haikal', '2b'),
	('a83', 'husnul fikri', '2b'),
	('a84', 'ifdhaly', '2b'),
	('a85', 'ismijar', '2b'),
	('a86', 'm. aufa rifqi', '2b'),
	('a87', 'm. ivan ilham', '2b'),
	('a88', 'marwazi', '2b'),
	('a89', 'muhammad abrar', '2b'),
	('a90', 'muhammad fatahazaki', '2b'),
	('a91', 'muhammad habil', '2b'),
	('a92', 'muhammad ihsan', '2b'),
	('a93', 'nadia', '2b'),
	('a94', 'nadia safira', '2b'),
	('a95', 'novi zahara', '2b'),
	('a96', 'nurul azizah', '2b'),
	('a97', 'prayanda wudatia', '2b'),
	('a98', 'putri balqis', '2b'),
	('a99', 'reza aulia', '2b'),
	('a100', 'saskia wulantari', '2b'),
	('a101', 'taqia aufa', '2b'),
	('a102', 'zakirullah', '2b'),
	('a103', 'zulfakar', '2b');